apiVersion: apps/v1
kind: Deployment
metadata:
  name: paragv14-deploy
  labels:
    app: paragv14-deploy-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paragv14-app
  template:
    metadata:
      labels:
        app: paragv14-app
    spec:
      containers:
      - name: paragv14-container
        image: paragv14/sa-mywebapp:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: paragv14-np-service
  labels:
    app: paragv14-np-app
spec:
  selector:
    app: paragv14-app

  type: NodePort
  ports:
  - nodePort: 31028
    port: 8080
    targetPort: 8080
